name: Build Dev

on:
  push:
    branches:
      - master

jobs:
  notify-action-init:
    name: Notify Action Init
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸğŸğŸ <a href="${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}">${{github.workflow}}</a>
            Repo: ${{github.repository}} 
            Initiated by <a href="${{github.server_url}}/${{github.actor}}">${{github.actor}}</a>.
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/smkt-eureka:dev

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  notify-final-ok:
    name: Notify Success 
    runs-on: ubuntu-latest
    needs: [sonar]
    if: ${{ success() }}
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸ†— ğŸ†— ğŸ†—
            The job Scan for SMKT_Eureka on branch ${{github.ref##*/}} <b>SUCCESS</b>.
            See the results <a href="https://sonarcloud.io/dashboard?id=AntonioAlejandro01_SMKT_Eureka">here</a>.
  notify-final-failure:
    name: Notify Failure 
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [sonar]
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸ›‘ ğŸ›‘ ğŸ›‘
            The job Scan for SMKT_Eureka on branch ${{github.ref##*/}} <b>FAILED</b>.
            Please, see what can was wrong <a href="https://sonarcloud.io/dashboard?id=AntonioAlejandro01_SMKT_Eureka">here</a>
  notify-final-docker-ok:
    name: Notify Docker Success 
    runs-on: ubuntu-latest
    needs: [sonar]
    if: ${{ success() }}
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸ†— ğŸ†— ğŸ†—
            The job Docker for SMKT_Eureka on branch ${{github.ref##*/}} <b>SUCCESS</b>.
  notify-final-docker-failure:
    name: Notify Docker Failure 
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [sonar]
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸ›‘ ğŸ›‘ ğŸ›‘
            The job Docker for SMKT_Eureka on branch ${{github.ref##*/}} <b>FAILED</b>.
