name: Build Dev

on:
  push:
    branches:
      - develop
jobs:
  notify-action-init:
    name: Notify Action Init
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸğŸğŸ 
            <a href="${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}">${{github.workflow}}</a>
            Repo: ${{github.repository}} 
            Initiated by <a href="${{github.server_url}}/${{github.actor}}">${{github.actor}}</a>.
  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [ sonar ]
    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/smkt-eureka:dev
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  notify-final-ok:
    name: Notify Success 
    runs-on: ubuntu-latest
    needs: [ sonar ]
    if: ${{ success() }}
    steps:
      - name: Query Git branch name
        uses: petehouston/github-actions-query-branch-name@892c80ceeff6234cd58701b5fea41e43b0398048
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸ†— ğŸ†— ğŸ†—
            The job Scan for SMKT_Eureka on branch <i>${{env.GIT_BRANCH_NAME}}</i> <b>SUCCESS</b>.
            See the results <a href="https://sonarcloud.io/dashboard?id=AntonioAlejandro01_SMKT_Eureka">here</a>.
  notify-final-failure:
    name: Notify Failure 
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [ sonar ]
    steps:
      - name: Query Git branch name
        uses: petehouston/github-actions-query-branch-name@892c80ceeff6234cd58701b5fea41e43b0398048
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸ›‘ ğŸ›‘ ğŸ›‘
            The job Scan for SMKT_Eureka on branch <i>${{env.GIT_BRANCH_NAME}}</i> <b>FAILED</b>.
            Please, see what can was wrong <a href="https://sonarcloud.io/dashboard?id=AntonioAlejandro01_SMKT_Eureka">here</a>
  notify-final-docker-ok:
    name: Notify Docker Success 
    runs-on: ubuntu-latest
    needs: [ docker ]
    if: ${{ success() }}
    steps:
      - name: Query Git branch name
        uses: petehouston/github-actions-query-branch-name@892c80ceeff6234cd58701b5fea41e43b0398048
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸ†— ğŸ†— ğŸ†—
            The job Docker for SMKT_Eureka on branch <i>${{env.GIT_BRANCH_NAME}}</i> <b>SUCCESS</b>.
  notify-final-docker-failure:
    name: Notify Docker Failure 
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [ docker ]
    steps:
      - name: Query Git branch name
        uses: petehouston/github-actions-query-branch-name@892c80ceeff6234cd58701b5fea41e43b0398048
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ğŸ›‘ ğŸ›‘ ğŸ›‘
            The job Docker for SMKT_Eureka on branch <i>${{env.GIT_BRANCH_NAME}}</i> <b>FAILED</b>.
